services:
  lb:
    image: traefik:v3
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
      - "--entrypoints.web.address=:80"
    networks:
      - calendar_network

  db:
    image: mysql:9
    container_name: calendar_mysql
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_calendar_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - calendar_network

  backend:
    container_name: calendar_backend
    restart: on-failure
    networks:
      - calendar_network
    depends_on:
      db:
        condition: service_healthy

  frontend:
    container_name: calendar_frontend
    restart: on-failure
    networks:
      - calendar_network

volumes:
  mysql_calendar_data:

networks:
  calendar_network:
    driver: bridge